### ISSUE TITLE
Product Roadmap

### ISSUE THREAD

**Issue by emadvote** [tcfev/forDem_documentation#1]
Currently there are 3 private projects including Kanban boards corresponding to each sub-project (website, app and backend)
We need to update the boards and make them public. 

- [ ] Add a link to the board to README

**Comment by lukas-h** [comment]
@armantorkzaban  and I created a *single* board, that now contains tasks for all repositories. It has dedicated views for each sub-project 

See here: https://github.com/orgs/tcfev/projects/7

**Comment by armantorkzaban** [comment]
Projects/7 is being actively used. Will close this one.
